# Generated by Django 6.0 on 2026-07-29 23:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolesUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El nombre no puede contener números ni caracteres especiales.', regex='^[a-zA-ZÁÉÍÓÚáéíóúñÑ\\s]+$')])),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rol - Unidad Orgánica',
                'verbose_name_plural': 'Roles - Unidades Orgánicas',
                'db_table': 'roles_units',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('names', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='El nombre no puede contener números ni caracteres especiales.', regex='^[a-zA-ZÁÉÍÓÚáéíóúñÑ\\s]+$')])),
                ('paternal_lastname', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='El nombre no puede contener números ni caracteres especiales.', regex='^[a-zA-ZÁÉÍÓÚáéíóúñÑ\\s]+$')])),
                ('maternal_lastname', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='El nombre no puede contener números ni caracteres especiales.', regex='^[a-zA-ZÁÉÍÓÚáéíóúñÑ\\s]+$')])),
                ('dni', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI debe contener exactamente 8 dígitos numéricos (ej: "12345678", "87654321").', regex='^\\d{8}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono/celular debe empezar con 9 y contener 8 dígitos más (ej: "912345678", "998765432").', regex='^[9]\\d{8}$')])),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'db_table': 'workers',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='El código de sucursal debe contener exactamente 3 dígitos numéricos (ej: "001", "002").', regex='^\\d{3}$')])),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El nombre no puede contener números ni caracteres especiales.', regex='^[a-zA-ZÁÉÍÓÚáéíóúñÑ\\s]+$')])),
                ('acronym', models.CharField(max_length=3, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches_district', to='places.district')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'branches',
            },
        ),
        migrations.CreateModel(
            name='OrganicUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El nombre no puede contener números ni caracteres especiales.', regex='^[a-zA-ZÁÉÍÓÚáéíóúñÑ\\s]+$')])),
                ('hierarchy_level', models.PositiveIntegerField()),
                ('parent_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organic_units_parent', to='organization.organicunit')),
            ],
            options={
                'verbose_name': 'Unidad Orgánica',
                'verbose_name_plural': 'Unidades Orgánicas',
                'db_table': 'organic_units',
            },
        ),
        migrations.CreateModel(
            name='BranchesOrganicUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches_organic_units_branch', to='organization.branch')),
                ('organic_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches_organic_units_organic_unit', to='organization.organicunit')),
            ],
            options={
                'verbose_name': 'Sucursal - Unidad Orgánica',
                'verbose_name_plural': 'Sucursales - Unidades Orgánicas',
                'db_table': 'branches_organic_units',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('branch_organic_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members_branch_organic_unit', to='organization.branchesorganicunit')),
                ('rol_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members_role_unit', to='organization.rolesunit')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members_worker', to='organization.worker')),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
                'db_table': 'members',
            },
        ),
    ]
