# Generated by Django 6.0 on 2026-07-23 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='branches',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='branchesorganicunit',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='members',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='organicunits',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='rolesunits',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='workers',
            managers=[
            ],
        ),
    ]
