# Generated by Django 6.0 on 2026-07-24 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_predictive', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=9, unique=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts_branches', to='organization.branches')),
                ('natural_phenomena', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts_natural_phenomena', to='core_predictive.naturalphenomenas')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'db_table': 'alerts',
            },
        ),
        migrations.CreateModel(
            name='AlertsPhases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fase de la Alerta',
                'verbose_name_plural': 'Fases de las Alertas',
                'db_table': 'alerts_phases',
            },
        ),
        migrations.CreateModel(
            name='AlertsStatuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estado de la Alerta',
                'verbose_name_plural': 'Estados de las Alertas',
                'db_table': 'alerts_statuses',
            },
        ),
        migrations.CreateModel(
            name='AlertsResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('alert_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='alerts_results_alert', serialize=False, to='alerts_management.alerts')),
                ('has_damage', models.BooleanField(default=False)),
                ('damage_report', models.TextField(blank=True, null=True)),
                ('taken_actions', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Resultado de Alerta',
                'verbose_name_plural': 'Resultados de Alertas',
                'db_table': 'alerts_result',
            },
        ),
        migrations.CreateModel(
            name='AlertsHistoric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('natural_phenomena_value', models.FloatField()),
                ('date_predicted_start', models.DateTimeField()),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts_historic_alert', to='alerts_management.alerts')),
                ('emcwf_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts_historic_emcwf_request', to='core_predictive.emcwfrequests')),
            ],
            options={
                'verbose_name': 'Histórico de Alertas',
                'verbose_name_plural': 'Históricos de Alertas',
                'db_table': 'alerts_historic',
            },
        ),
        migrations.CreateModel(
            name='AlertNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert_historic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts_notifications_alerts_historic', to='alerts_management.alertshistoric')),
            ],
            options={
                'verbose_name': 'Notificación de Alerta',
                'verbose_name_plural': 'Notificaciones de Alertas',
                'db_table': 'alert_notifications',
            },
        ),
        migrations.CreateModel(
            name='AlertsStatusesPhases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('alert_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_statuses_phases_phase', to='alerts_management.alertsphases')),
                ('alert_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_statuses_phases_status', to='alerts_management.alertsstatuses')),
            ],
            options={
                'verbose_name': 'Estado y Fase de la Alerta',
                'verbose_name_plural': 'Estados y Fases de las Alertas',
                'db_table': 'alerts_statuses_phases',
                'unique_together': {('alert_status', 'alert_phase')},
            },
        ),
        migrations.AddField(
            model_name='alertshistoric',
            name='alert_status_phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts_historic_status_phase', to='alerts_management.alertsstatusesphases'),
        ),
    ]
