# Generated by Django 6.0 on 2026-07-29 23:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='El valor debe contener únicamente caracteres numéricos (0-9) y tener una longitud de 9 dígitos.', regex='^\\d{9}$')])),
                ('peak_intensity_mm_h', models.DecimalField(decimal_places=2, max_digits=6)),
                ('start_time_utc', models.DateTimeField()),
                ('end_time_utc', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'db_table': 'alerts',
            },
        ),
        migrations.CreateModel(
            name='AlertClusters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cluster de Alerta',
                'verbose_name_plural': 'Clusters de Alertas',
                'db_table': 'alerts_clusters',
            },
        ),
        migrations.CreateModel(
            name='AlertClustersComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Componente de Cluster de Alerta',
                'verbose_name_plural': 'Componentes de Clusters de Alertas',
                'db_table': 'alerts_clusters_components',
            },
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Histórico de Alertas',
                'verbose_name_plural': 'Históricos de Alertas',
                'db_table': 'alerts_historic',
            },
        ),
        migrations.CreateModel(
            name='AlertNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificación de Alerta',
                'verbose_name_plural': 'Notificaciones de Alerta',
                'db_table': 'alert_notifications',
            },
        ),
        migrations.CreateModel(
            name='AlertPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='El nombre no puede contener números ni caracteres especiales.', regex='^[a-zA-ZÁÉÍÓÚáéíóúñÑ\\s]+$')])),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fase de la Alerta',
                'verbose_name_plural': 'Fases de las Alertas',
                'db_table': 'alerts_phases',
            },
        ),
        migrations.CreateModel(
            name='AlertStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='El nombre no puede contener números ni caracteres especiales.', regex='^[a-zA-ZÁÉÍÓÚáéíóúñÑ\\s]+$')])),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estado de la Alerta',
                'verbose_name_plural': 'Estados de las Alertas',
                'db_table': 'alerts_statuses',
            },
        ),
        migrations.CreateModel(
            name='AlertStatusPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estado y Fase de la Alerta',
                'verbose_name_plural': 'Estados y Fases de las Alertas',
                'db_table': 'alerts_statuses_phases',
            },
        ),
        migrations.CreateModel(
            name='AlertResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='alerts_results_alert', serialize=False, to='alerts_management.alert')),
                ('has_damage', models.BooleanField(default=False)),
                ('damage_report', models.TextField(blank=True, null=True)),
                ('taken_actions', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Resultado de Alerta',
                'verbose_name_plural': 'Resultados de Alertas',
                'db_table': 'alerts_result',
            },
        ),
    ]
