# Generated by Django 6.0 on 2026-07-29 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts_management', '0001_initial'),
        ('components', '0001_initial'),
        ('core_predictive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='max_threshold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts_max_threshold', to='core_predictive.thresholdsnaturalphenomena'),
        ),
        migrations.AddField(
            model_name='alert',
            name='natural_phenomena',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts_natural_phenomena', to='core_predictive.naturalphenomena'),
        ),
        migrations.AddField(
            model_name='alertclusters',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts_clusters_alerts', to='alerts_management.alert'),
        ),
        migrations.AddField(
            model_name='alertclusters',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts_clusters_clusters_snapshots', to='core_predictive.gfsclustersnapshot'),
        ),
        migrations.AddField(
            model_name='alertclusterscomponents',
            name='alert_cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts_clusters_components_clusters', to='alerts_management.alertclusters'),
        ),
        migrations.AddField(
            model_name='alertclusterscomponents',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts_clusters_components_components', to='components.component'),
        ),
        migrations.AddField(
            model_name='alerthistory',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts_historic_alert', to='alerts_management.alert'),
        ),
        migrations.AddField(
            model_name='alertnotification',
            name='alert_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts_notifications_alerts_history', to='alerts_management.alerthistory'),
        ),
        migrations.AddField(
            model_name='alertstatusphase',
            name='alert_phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_statuses_phases_phase', to='alerts_management.alertphase'),
        ),
        migrations.AddField(
            model_name='alertstatusphase',
            name='alert_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_statuses_phases_status', to='alerts_management.alertstatus'),
        ),
        migrations.AddField(
            model_name='alerthistory',
            name='alert_status_phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts_historic_status_phase', to='alerts_management.alertstatusphase'),
        ),
        migrations.AddIndex(
            model_name='alertclusters',
            index=models.Index(fields=['alert', 'cluster'], name='alerts_clus_alert_i_835555_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='alertclusters',
            unique_together={('alert', 'cluster')},
        ),
        migrations.AddIndex(
            model_name='alertclusterscomponents',
            index=models.Index(fields=['alert_cluster', 'component'], name='alerts_clus_alert_c_d8d866_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='alertclusterscomponents',
            unique_together={('alert_cluster', 'component')},
        ),
        migrations.AlterUniqueTogether(
            name='alertstatusphase',
            unique_together={('alert_status', 'alert_phase')},
        ),
    ]
