# Generated by Django 6.0 on 2026-07-23 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='alertsphases',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='alertsresult',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='alertsstatuses',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='alertsstatusesphases',
            managers=[
            ],
        ),
    ]
