# Generated by Django 6.0 on 2026-07-30 00:48

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_management', '0002_initial'),
        ('core_predictive', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='alertclusters',
            name='alerts_clus_alert_i_835555_idx',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='peak_intensity_mm_h',
        ),
        migrations.AddField(
            model_name='alert',
            name='max_intensity_mm_h',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='alertclusters',
            name='is_active_forecast',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alertclusters',
            name='representative_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Punto Representativo de Impacto'),
        ),
        migrations.AddField(
            model_name='alertclusterscomponents',
            name='intensity_at_component',
            field=models.FloatField(default=0.0, verbose_name='Intensidad estimada en la infraestructura (mm/h)'),
        ),
        migrations.AddField(
            model_name='alerthistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alerts_historic_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertnotification',
            name='channel',
            field=models.CharField(choices=[('TELEGRAM', 'Telegram'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Correo Electrónico')], default='TELEGRAM', max_length=20),
        ),
        migrations.AddField(
            model_name='alertnotification',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='¿Fue despachado con éxito?'),
        ),
        migrations.AddField(
            model_name='alertnotification',
            name='notification_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Cancelación o Reajuste'),
        ),
        migrations.AddField(
            model_name='alertnotification',
            name='notification_type',
            field=models.CharField(choices=[('INITIAL', 'Alerta Inicial'), ('RESCHEDULED', 'Reprogramación Horaria'), ('CANCELLED', 'Cancelación / Rectificación'), ('EXPIRED', 'Cierre Nominal')], default='INITIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='alertnotification',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora de Envío Real'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='code',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='El valor debe contener únicamente caracteres numéricos (0-9) y tener una longitud de 9 dígitos.', regex='^\\d{9}$')], verbose_name='Código Único de Alerta (000000001)'),
        ),
        migrations.AddIndex(
            model_name='alertclusters',
            index=models.Index(fields=['alert', 'cluster', 'is_active_forecast'], name='alerts_clus_alert_i_db6b8e_idx'),
        ),
        migrations.AddIndex(
            model_name='alerthistory',
            index=models.Index(fields=['alert', 'created_at'], name='alerts_hist_alert_i_a92757_idx'),
        ),
        migrations.AddIndex(
            model_name='alertnotification',
            index=models.Index(fields=['alert_history', 'is_sent', 'notification_type'], name='alert_notif_alert_h_b228b8_idx'),
        ),
    ]
