# Generated by Django 6.0 on 2026-07-30 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_management', '0003_remove_alertclusters_alerts_clus_alert_i_835555_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alertstatusphase',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='alerthistory',
            name='alert_status_phase',
        ),
        migrations.AddField(
            model_name='alerthistory',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historic_phase', to='alerts_management.alertphase'),
        ),
        migrations.AddField(
            model_name='alerthistory',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historic_status', to='alerts_management.alertstatus'),
        ),
        migrations.AddField(
            model_name='alertstatus',
            name='phases',
            field=models.ManyToManyField(related_name='statuses', through='alerts_management.AlertStatusPhase', to='alerts_management.alertphase'),
        ),
        migrations.AlterField(
            model_name='alerthistory',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historic_alert', to='alerts_management.alert'),
        ),
        migrations.AlterField(
            model_name='alerthistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historic_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alertstatusphase',
            name='alert_phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_phase_statuses', to='alerts_management.alertphase'),
        ),
        migrations.AlterField(
            model_name='alertstatusphase',
            name='alert_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_status_phases', to='alerts_management.alertstatus'),
        ),
        migrations.AddConstraint(
            model_name='alertstatusphase',
            constraint=models.UniqueConstraint(fields=('alert_status', 'alert_phase'), name='unique_alert_status_phase'),
        ),
    ]
