# Generated by Django 6.0 on 2026-07-30 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_management', '0004_alter_alertstatusphase_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertstatusphase',
            name='alert_phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_phase_statuses', to='alerts_management.alertphase'),
        ),
    ]
