# Generated by Django 6.0 on 2026-09-03 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_management', '0005_alter_alertstatusphase_alert_phase'),
        ('core_predictive', '0005_threshold_severity_level_alter_threshold_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerthistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Histórico de Alertas', 'verbose_name_plural': 'Históricos de Alertas'},
        ),
        migrations.AlterModelOptions(
            name='alertnotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notificación de Alerta', 'verbose_name_plural': 'Notificaciones de Alerta'},
        ),
        migrations.AddField(
            model_name='alert',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='max_threshold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts_max_threshold', to='core_predictive.threshold'),
        ),
        migrations.AlterField(
            model_name='alertnotification',
            name='alert_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alert_notifications_alerts_history', to='alerts_management.alerthistory'),
        ),
        migrations.AlterUniqueTogether(
            name='alerthistory',
            unique_together={('alert', 'status', 'phase')},
        ),
    ]
