# Generated by Django 6.0 on 2026-09-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_management', '0006_alter_alerthistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='real_start_time_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora real de inicio del fenómeno (confirmación)'),
        ),
    ]
