# Generated by Django 6.0 on 2026-07-23 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_shared', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SoftDeleteManager',
        ),
    ]
