services:
  # =========== DATABASE =========== 
  db_postgis:
    image: postgis/postgis:18-3.6
    container_name: eps_siac_db_postgis
    volumes:
      - eps_siac_data_db:/var/lib/postgresql
    networks:
      - eps_siac_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s

  # =========== API (DJANGO) =========== 
  api:
    container_name: eps_siac_api
    networks:
      - eps_siac_network
    restart: on-failure:2
    depends_on:
      db_postgis:
        condition: service_healthy

  # =========== REDIS =========== 
  redis:
    image: redis:7-alpine
    container_name: eps_redis
    ports:
      - "6379:6379"

  # =========== FRONTEND (REACT) =========== 
  frontend:
    container_name: eps_siac_frontend
    networks: 
      - eps_siac_network
    depends_on:
      - api
    

volumes:
  eps_siac_data_db: # local por defecto

networks:
  eps_siac_network:
    driver: bridge