services:
  # =========== DATABASE =========== 
  db_postgis:
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    # Indicamos la ruta del .env de produccion
    env_file:
      - ./backend/.env.prod

  # =========== API (DJANGO) =========== 
  api:
    build:
      context: ./backend
      target: prod
    env_file:
      - ./backend/.env.prod
    volumes:
      - gfs_media_data:/app/storage
      
  # =========== CELERY () =========== 
  celery_worker:
    build:
      context: ./backend
      target: prod
    container_name: eps_siac_celery_worker
    command: celery -A EPS_SelvaCentral worker --loglevel=info --concurrency=2
    volumes:
      - gfs_media_data:/app/storage
    depends_on:
      - redis
      - api
    
  celery_beat:
    build:
      context: ./backend
      target: prod
    container_name: eps_siac_celery_beat
    command: celery -A EPS_SelvaCentral beat --loglevel=info
    depends_on:
      - redis
      - celery_worker

  # =========== FRONTEND (REACT) =========== 
  frontend:
    build:
      context: ./frontend
      target: prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    environment:
      # Utilizamos la variable declarada en el env_file del frontend
      - SITE_ADDRESS
    env_file:
      - ./frontend/.env.prod

volumes:
  caddy_data:
  caddy_config:
  gfs_media_data: