services:
  # =========== DATABASE =========== 
  db_postgis:
    # Indicamos la ruta del .env de desarrollo
    env_file:
      - ./backend/.env.dev
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-eps_siac}
    ports:
      - "5435:5432"

  # =========== API (DJANGO) =========== 
  api:
    build:
      context: ./backend
      target: dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/app
    env_file:
      - ./backend/.env.dev
  
  # =========== CELERY () =========== 
  celery_worker:
    build:
      context: ./backend
      target: dev
    container_name: eps_siac_celery_worker
    command: celery -A EPS_SelvaCentral worker --loglevel=info --concurrency=2
    volumes:
      - .:/app
      - /app/storage:/app/storage
    depends_on:
      - redis
      - api
    
  celery_beat:
    build:
      context: ./backend
      target: dev
    container_name: eps_siac_celery_beat
    command: celery -A EPS_SelvaCentral beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - celery_worker
  
  # =========== FRONTEND (REACT) =========== 
  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    environment:
      # Utilizamos la variable declarada en el env_file del frontend
      - SITE_ADDRESS
    env_file:
      - ./frontend/.env.dev