services:
  # =========== DATABASE =========== 
  db_postgis:
    # Indicamos la ruta del .env de desarrollo
    env_file:
      - ./backend/.env.dev
    ports:
      - "5435:5432"
    networks:
      - eps_siac_network

  # =========== API (DJANGO) ===========
  api:
    build:
      context: ./backend
      target: dev
    ports:
      - "8000:8000"
    environment:
      - CONTAINER_ROLE=api
    volumes:
      - ./backend/:/app
    env_file:
      - ./backend/.env.dev
    networks:
      - eps_siac_network

# =========== CELERY () =========== 
  celery_worker:
    build:
      context: ./backend
      target: dev
    container_name: eps_siac_celery_worker
    command: celery -A EPS_SelvaCentral worker --loglevel=info --concurrency=2
    volumes:
      - ./backend/:/app
    env_file:
      - ./backend/.env.dev
    environment:
      - CONTAINER_ROLE=worker
    networks:
      - eps_siac_network
    depends_on:
      api:
        condition: service_healthy
      db_postgis:
        condition: service_healthy
      redis:
        condition: service_started
    
  celery_beat:
    build:
      context: ./backend
      target: dev
    container_name: eps_siac_celery_beat
    command: celery -A EPS_SelvaCentral beat --loglevel=info
    volumes:
      - ./backend/:/app
    env_file:
      - ./backend/.env.dev
    environment:
      - CONTAINER_ROLE=beat
    networks:
      - eps_siac_network
    depends_on:
      api:
        condition: service_healthy
      db_postgis:
        condition: service_healthy
      redis:
        condition: service_started
  
  # =========== FRONTEND (REACT) =========== 
  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env.dev