services:
  # =========== DATABASE =========== 
  db_postgis:
    env_file:
      - ./backend/.env.prod
    volumes:
      - db_data:/var/lib/postgresql
    networks:
      - eps_siac_network

  # =========== API (DJANGO) =========== 
  api:
    build:
      context: ./backend
      target: prod
    env_file:
      - ./backend/.env.prod
    volumes:
      - gfs_media_data:/app/storage
    environment:
      - CONTAINER_ROLE=api
    networks:
      - eps_siac_network
      
  # =========== CELERY () =========== 
  celery_worker:
    build:
      context: ./backend
      target: prod
    container_name: eps_siac_celery_worker
    command: celery -A EPS_SelvaCentral worker --loglevel=info --concurrency=2
    volumes:
      - gfs_media_data:/app/storage
    env_file:
      - ./backend/.env.prod
    environment:
      - CONTAINER_ROLE=worker
    depends_on:
      redis:
        condition: service_started
      api:
        condition: service_healthy
    networks:
      - eps_siac_network
    
  celery_beat:
    build:
      context: ./backend
      target: prod
    container_name: eps_siac_celery_beat
    command: celery -A EPS_SelvaCentral beat --loglevel=info
    env_file:
      - ./backend/.env.prod
    environment:
      - CONTAINER_ROLE=beat
    networks:
      - eps_siac_network
    depends_on:
      redis:
        condition: service_started
      celery_worker:
        condition: service_started

  # =========== FRONTEND (REACT) =========== 
  frontend:
    build:
      context: ./frontend
      target: prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - ./frontend/.env.prod
    networks:
      - eps_siac_network

volumes:
  db_data:
  caddy_data:
  caddy_config:
  gfs_media_data: