services:
  db_postgis:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=eps_siac
    ports:
      - "5435:5432"

  # api:
  #   image: python:3.15.0b3-bookworm
  #   container_name: eps_siac_api
  #   ports:
  #     - "8001:8000"
  #   volumes:
  #     - ./EPS_SelvaCentral
  #   command: python manage.py runserver
  #   env_file:
  #     - ./EPS_SelvaCentral/.env
  #   networks:
  #     - eps_siac_network
  #   depends_on:
  #       condition: service_healthy

volumes:
  eps_siac_data_db: # local por defecto

networks:
  eps_siac_network: # bridge por defecto
