# Generated by Django 6.0 on 2026-07-23 22:51

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMCWFRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('request_code', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(max_length=20)),
                ('TargetVariable', models.CharField(max_length=50)),
                ('DateRangeStart', models.DateField()),
                ('DateRangeEnd', models.DateField()),
                ('GeomBounds', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Límite Geométrico WGS84')),
                ('FileName', models.CharField(max_length=200)),
                ('FilePath', models.CharField(max_length=200)),
                ('FileSizeMb', models.FloatField()),
                ('DownloandTimeSeconds', models.FloatField()),
            ],
            options={
                'verbose_name': 'Solicitud EMCWF',
                'verbose_name_plural': 'Solicitudes EMCWF',
                'db_table': 'emcwf_requests',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='NaturalPhenomenas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fenómeno Natural',
                'verbose_name_plural': 'Fenómenos Naturales',
                'db_table': 'natural_phenomenas',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Thresholds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Umbral',
                'verbose_name_plural': 'Umbrales',
                'db_table': 'thresholds',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UnitsMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'units_measurement',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='VariableTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Variable',
                'verbose_name_plural': 'Tipos de Variables',
                'db_table': 'variable_types',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables_unit_measurement', to='core_predictive.unitsmeasurement')),
                ('variable_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables_variable_type', to='core_predictive.variabletypes')),
            ],
            options={
                'verbose_name': 'Variable',
                'verbose_name_plural': 'Variables',
                'db_table': 'variables',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ThresholdsNaturalPhenomenas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds_natural_phenomenas_district', to='places.district')),
                ('natural_phenomena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds_natural_phenomenas_natural_phenomena', to='core_predictive.naturalphenomenas')),
                ('threshold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds_natural_phenomenas_threshold', to='core_predictive.thresholds')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds_natural_phenomenas_variable', to='core_predictive.variables')),
            ],
            options={
                'verbose_name': 'Umbral - Fenómeno Natural',
                'verbose_name_plural': 'Umbrales - Fenómenos Naturales',
                'db_table': 'thresholds_natural_phenomenas',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='NaturalPhenomenasVariables',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('pk', models.CompositePrimaryKey('natural_phenomena', 'variable', blank=True, editable=False, primary_key=True, serialize=False)),
                ('natural_phenomena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natural_phenomenas_variables_natural_phenomena', to='core_predictive.naturalphenomenas')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natural_phenomenas_variables_variable', to='core_predictive.variables')),
            ],
            options={
                'verbose_name': 'Fenómeno Natural - Variable',
                'verbose_name_plural': 'Fenómenos Naturales - Variables',
                'db_table': 'natural_phenomenas_variables',
                'unique_together': {('natural_phenomena', 'variable')},
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
