# Generated by Django 6.0 on 2026-07-29 23:53

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='GFSRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('request_code', models.CharField(max_length=100, unique=True, verbose_name='Código de Solicitud')),
                ('status', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El nombre no puede contener números ni caracteres especiales.', regex='^[a-zA-ZÁÉÍÓÚáéíóúñÑ\\s]+$')])),
                ('target_variable', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='El nombre no puede contener números ni caracteres especiales.', regex='^[a-zA-ZÁÉÍÓÚáéíóúñÑ\\s]+$')])),
                ('date_range_start', models.DateTimeField(verbose_name='Inicio del Pronóstico (UTC)')),
                ('date_range_end', models.DateTimeField(verbose_name='Fin del Pronóstico (UTC)')),
                ('geom_bounds', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Límite Geométrico WGS84 de la petición.')),
                ('file_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Archivo')),
                ('file_path', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ruta del Archivo grib2 o netcdf')),
                ('file_size_mb', models.FloatField(blank=True, null=True, verbose_name='Tamaño del Archivo (MB)')),
                ('download_time_seconds', models.FloatField(blank=True, null=True, verbose_name='Tiempo de Descarga (segundos)')),
            ],
            options={
                'verbose_name': 'Solicitud GFS',
                'verbose_name_plural': 'Solicitudes GFS',
                'db_table': 'gfs_requests',
            },
        ),
        migrations.CreateModel(
            name='NaturalPhenomena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='El nombre no puede contener números ni caracteres especiales.', regex='^[a-zA-ZÁÉÍÓÚáéíóúñÑ\\s]+$')])),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='El nombre no puede contener números ni caracteres especiales.', regex='^[a-zA-ZÁÉÍÓÚáéíóúñÑ\\s]+$')])),
            ],
            options={
                'verbose_name': 'Fenómeno Natural',
                'verbose_name_plural': 'Fenómenos Naturales',
                'db_table': 'natural_phenomenas',
            },
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='El nombre no puede contener números ni caracteres especiales.', regex='^[a-zA-ZÁÉÍÓÚáéíóúñÑ\\s]+$')])),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='El nombre no puede contener números ni caracteres especiales.', regex='^[a-zA-ZÁÉÍÓÚáéíóúñÑ\\s]+$')])),
            ],
            options={
                'verbose_name': 'Umbral',
                'verbose_name_plural': 'Umbrales',
                'db_table': 'thresholds',
            },
        ),
        migrations.CreateModel(
            name='UnitsMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='El nombre no puede contener números ni caracteres especiales.', regex='^[a-zA-ZÁÉÍÓÚáéíóúñÑ\\s]+$')])),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='El nombre no puede contener números ni caracteres especiales.', regex='^[a-zA-ZÁÉÍÓÚáéíóúñÑ\\s]+$')])),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'units_measurement',
            },
        ),
        migrations.CreateModel(
            name='VariableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='El nombre no puede contener números ni caracteres especiales.', regex='^[a-zA-ZÁÉÍÓÚáéíóúñÑ\\s]+$')])),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='El nombre no puede contener números ni caracteres especiales.', regex='^[a-zA-ZÁÉÍÓÚáéíóúñÑ\\s]+$')])),
            ],
            options={
                'verbose_name': 'Tipo de Variable',
                'verbose_name_plural': 'Tipos de Variables',
                'db_table': 'variable_types',
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='El nombre no puede contener números ni caracteres especiales.', regex='^[a-zA-ZÁÉÍÓÚáéíóúñÑ\\s]+$')])),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='El nombre no puede contener números ni caracteres especiales.', regex='^[a-zA-ZÁÉÍÓÚáéíóúñÑ\\s]+$')])),
                ('unit_measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables_unit_measurement', to='core_predictive.unitsmeasurement')),
                ('variable_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables_variable_type', to='core_predictive.variabletype')),
            ],
            options={
                'verbose_name': 'Variable',
                'verbose_name_plural': 'Variables',
                'db_table': 'variables',
            },
        ),
        migrations.CreateModel(
            name='ThresholdsNaturalPhenomena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds_district', to='places.district')),
                ('natural_phenomena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds_natural_phenomena', to='core_predictive.naturalphenomena')),
                ('threshold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds_threshold', to='core_predictive.threshold')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds_variable', to='core_predictive.variable')),
            ],
            options={
                'verbose_name': 'Umbral - Fenómeno Natural',
                'verbose_name_plural': 'Umbrales - Fenómenos Naturales',
                'db_table': 'thresholds_natural_phenomenas',
            },
        ),
        migrations.CreateModel(
            name='GFSActiveCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('max_intensity_mm_h', models.FloatField(verbose_name='Intensidad Pico (mm/h)')),
                ('intensity_series', models.JSONField(verbose_name='Serie Temporal Horaria [t1..t12]')),
                ('timestamps', models.JSONField(blank=True, null=True, verbose_name='Marcas de Tiempo Horarias [t1..t12]')),
                ('threshold_names', models.JSONField(blank=True, null=True, verbose_name='Nombres de Umbral [t1..t12]')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Geometría Celda')),
                ('gfs_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gfs_cells', to='core_predictive.gfsrequest')),
            ],
            options={
                'verbose_name': 'Celda Activa GFS',
                'verbose_name_plural': 'Celdas Activas GFS',
                'db_table': 'gfs_active_cells',
                'indexes': [models.Index(fields=['gfs_request', 'max_intensity_mm_h'], name='gfs_active__gfs_req_46cd5d_idx')],
            },
        ),
        migrations.CreateModel(
            name='GFSClusterSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_step', models.IntegerField(verbose_name='Paso Horario (1..12)')),
                ('timestamp_str', models.CharField(max_length=50, verbose_name='Fecha/Hora Legible (PET)')),
                ('cluster_index', models.IntegerField(verbose_name='Índice de Clúster (DBSCAN ID)')),
                ('total_cells', models.IntegerField(verbose_name='Cantidad de Celdas Agrupadas')),
                ('max_intensity_mm_h', models.FloatField(verbose_name='Intensidad Máxima (mm/h)')),
                ('avg_intensity_mm_h', models.FloatField(verbose_name='Intensidad Promedio (mm/h)')),
                ('affected_ubigeos', models.JSONField(default=list, verbose_name='Lista de UBIGEOS Afectados')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Geometría Disuelta Clúster')),
                ('gfs_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='core_predictive.gfsrequest')),
                ('threshold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core_predictive.threshold', verbose_name='Umbral Asignado')),
            ],
            options={
                'db_table': 'gfs_cluster_snapshots',
                'ordering': ['time_step', 'cluster_index'],
                'indexes': [models.Index(fields=['gfs_request', 'time_step'], name='gfs_cluster_gfs_req_908277_idx')],
            },
        ),
        migrations.CreateModel(
            name='NaturalPhenomenasVariables',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('pk', models.CompositePrimaryKey('natural_phenomena', 'variable', blank=True, editable=False, primary_key=True, serialize=False)),
                ('natural_phenomena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natural_phenomenas_variables_natural_phenomena', to='core_predictive.naturalphenomena')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natural_phenomenas_variables_variable', to='core_predictive.variable')),
            ],
            options={
                'verbose_name': 'Fenómeno Natural - Variable',
                'verbose_name_plural': 'Fenómenos Naturales - Variables',
                'db_table': 'natural_phenomenas_variables',
                'unique_together': {('natural_phenomena', 'variable')},
            },
        ),
    ]
