# Generated by Django 6.0 on 2026-07-23 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_predictive', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='emcwfrequests',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='naturalphenomenas',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='naturalphenomenasvariables',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='thresholds',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='thresholdsnaturalphenomenas',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='unitsmeasurement',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='variables',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='variabletypes',
            managers=[
            ],
        ),
    ]
