# Generated by Django 6.0 on 2026-07-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_predictive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gfsclustersnapshot',
            name='timestamp_str',
            field=models.CharField(max_length=50, verbose_name='Fecha/Hora Legible (UTC)'),
        ),
    ]
