# Generated by Django 6.0 on 2026-07-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_predictive', '0002_alter_gfsclustersnapshot_timestamp_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gfsclustersnapshot',
            name='timestamp_str',
        ),
        migrations.AddField(
            model_name='gfsclustersnapshot',
            name='timestamp_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora UTC del Clúster'),
        ),
        migrations.AddIndex(
            model_name='gfsclustersnapshot',
            index=models.Index(fields=['timestamp_utc'], name='gfs_cluster_timesta_efd55c_idx'),
        ),
    ]
