# Generated by Django 6.0 on 2026-08-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_predictive', '0003_remove_gfsclustersnapshot_timestamp_str_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gfsactivecell',
            name='district_ubigeos',
            field=models.JSONField(default=list, verbose_name='Lista de UBIGEOS Afectados'),
        ),
    ]
