# Generated by Django 6.0 on 2026-09-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_predictive', '0004_gfsactivecell_district_ubigeos'),
    ]

    operations = [
        migrations.AddField(
            model_name='threshold',
            name='severity_level',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Nivel de Severidad (Mayor número = Mayor peligro)'),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
