"""
Django settings for EPS_SelvaCentral project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from celery.schedules import crontab
from pathlib import Path
from datetime import timedelta

import os
import environ


BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False)
)

ENVIRONMENT = os.getenv('DJANGO_ENV', 'dev')
env_file = BASE_DIR / f".env.{ENVIRONMENT}"

if env_file.exists():
    environ.Env.read_env(str(env_file))
else:
    environ.Env.read_env(str(BASE_DIR / ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY", default="default-secret-key-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG", default=False)

ALLOWED_HOSTS = env("ALLOWED_HOSTS", default=["*", "localhost"])

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    # 'django.contrib.gis',

    # Añadimos el framework backend
    'rest_framework',
    'rest_framework.authtoken',  # Requerido por dj-rest-auth
    'corsheaders', # Para consumo desde frontend externo

    # Autenticación mediante JWT
    'dj_rest_auth',
    'rest_framework_simplejwt',
    'django.contrib.sites',

    # Documentación
    'drf_spectacular',

    # Añadimos nuestras aplicaciones
    'precipitations',
    'authentication',
    'alerts_management',
    'components',
    'core_predictive',
    'core_shared',
    'organization',
    'places'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173", # Si usa Vite
    "http://localhost:3000", # Si usa Create React App,
    "http://172.24.0.4:5173"
]

ROOT_URLCONF = 'EPS_SelvaCentral.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'EPS_SelvaCentral.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'eps_siac',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'db_postgis',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
SITE_ID = 1

# Configurate REST Framework to imperant auth by default
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),

    # Spectacular
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    # Paginación por defecto
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'EPS SIAC API',
    'DESCRIPTION': 'API para el sistema de información hidrológica de la EPS Selva Central',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SECURITY': [{'jwt': []}],
    'SECURITY_DEFINITIONS': {
        'jwt': {
            'type': 'apiKey',
            'in': 'header',
            'name': 'Authorization',
            'description': 'Ingrese el token en formato: Bearer <su_access_token>'
        }
    }
}

# dj-rest-auth use JWT instead of standard Tokens
REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_HTTPONLY': False,  # Desactiva la restricción de cookies HttpOnly
    'JWT_AUTH_HEADER_PREFIX': 'Bearer',
    # Serializer del perfil del propio usuario (GET/PATCH /auth/user/).
    # Se extiende para incluir `is_staff`/`is_superuser` y permitir al
    # frontend decidir qué mostrar según el rol del usuario autenticado.
    'USER_DETAILS_SERIALIZER': 'authentication.serializers.UserDetailsSerializer',
}

# Configuración del Broker y Resultados (Redis)
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://redis:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://redis:6379/0')

# Formatos de serialización seguros para geoprocesamiento
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC' # El schedule usará la zona horario global UTC
CELERY_ENABLE_UTC = True

# === Caché y Locks (Redis compartido entre procesos) ===
# Por defecto Django usa LocMemCache (caché en memoria POR PROCESO), lo que impide:
#   1) Que un worker de Celery invalide la caché de la API (el timeline no se refrescaba).
#   2) Que el lock Redis (`cache.add`) funcione entre workers (doble descarga al mismo .nc).
# Usamos Redis DB 1 para no chocar con el broker/result backend de Celery (DB 0).
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': os.getenv('CACHE_URL', 'redis://redis:6379/1'),
    }
}

# === Planificador Periódico (Celery Beat) ===
CELERY_BEAT_SCHEDULE = {
    'descarga-automatica-gfs-diaria': {
        # === Nombre de la tarea a ejecutar ===
        'task': 'core_predictive.tasks.run_scheduled_gfs_download',

        # === Programación de ejecución (08:15 y 20:15 UTC todos los días) ===
        # Los valores se establecen en base a las horas de ejecución del modelo, solo que 1 hora después para evitar problemas y garantizar la descarga.
        # 00/24 UTC + 1:00 (periodo adicional) => 1:00 UTC (20:00 -> Perú)
        # 06 UTC + 1:00 (periodo adicional) => 7:00 UTC (02:00 -> Perú)
        # 12 UTC + 1:00 (periodo adicional) => 13:00 UTC (08:00 -> Perú)
        # 18 UTC + 1:00 (periodo adicional) => 19:00 UTC (14:00 -> Perú)
        #
        # === FIX ===
        # Sin `minute=0` explícito, Celery interpreta `minute='*'` (default) y dispara
        # 60 tareas por hora en vez de 1. Eso producía el spam de "Skip Task" en el log.
        # Ver https://docs.celeryq.dev/en/stable/userguide/periodic-tasks.html#crontab-schedules
        'schedule': crontab(hour='1,7,13,19', minute=0),
    },

    'despacho-horario-alertas-telegram': {
        'task': 'tasks.dispatch_hourly_alerts',
        'schedule': crontab(minute=0),  # Se ejecuta al minuto 0 de cada hora (Ej: 01:00, 02:00, etc.)
    },

    'evaluacion-timeouts-maquina-estados': {
        'task': 'tasks.process_state_machine_timeouts',
        'schedule': crontab(minute=5),  # Se ejecuta cada hora al minuto 05 para dar margen
    },
}

# === Configuración almacenamiento del modelo GFS ===
GFS_STORAGE_DIR = env('GFS_STORAGE_DIR', default='/app/storage')

# MEDIA_ROOT: Ruta donde están físicamente los archivos en disco
MEDIA_ROOT = GFS_STORAGE_DIR

# MEDIA_URL: PREFIJO que usará Django para las peticiones web HTTP
MEDIA_URL = '/media/'

os.makedirs(MEDIA_ROOT, exist_ok=True)

# === Configuración de Telegram ===
TELEGRAM_BOT_TOKEN = env('TELEGRAM_BOT_TOKEN', default=None)
TELEGRAM_CHAT_ID = env('TELEGRAM_CHAT_ID', default=None)

