# Generated by Django 6.0 on 2026-07-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='department',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='district',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='province',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='sector',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
