# Generated by Django 6.0 on 2026-07-24 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='department',
            field=models.ForeignKey(db_column='department', on_delete=django.db.models.deletion.PROTECT, related_name='provinces', to='places.department'),
        ),
    ]
