# Generated by Django 6.0 on 2026-07-24 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_province_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='province',
            field=models.ForeignKey(db_column='province_ubigeo', on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='places.province'),
        ),
        migrations.AlterField(
            model_name='province',
            name='department',
            field=models.ForeignKey(db_column='department_ubigeo', on_delete=django.db.models.deletion.PROTECT, related_name='provinces', to='places.department'),
        ),
    ]
