# Generated by Django 6.0 on 2026-07-25 03:39

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0004_department_geometry_district_geometry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El nombre no puede contener números ni caracteres especiales.', regex='^[a-zA-ZÁÉÍÓÚáéíóúñÑ\\s]+$')])),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Componente',
                'verbose_name_plural': 'Tipos de Componentes',
                'db_table': 'type_components',
            },
        ),
        migrations.CreateModel(
            name='Criticality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='El nombre no puede contener números ni caracteres especiales.', regex='^[a-zA-ZÁÉÍÓÚáéíóúñÑ\\s]+$')])),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Criticidad',
                'verbose_name_plural': 'Criticidades',
                'db_table': 'criticalities',
            },
        ),
        migrations.CreateModel(
            name='OperationalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='El código de estado operativo debe contener exactamente 3 caracteres alfanuméricos (ej: "ACT", "DIS").', regex='^[A-Z]{3}$')])),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El nombre no puede contener números ni caracteres especiales.', regex='^[a-zA-ZÁÉÍÓÚáéíóúñÑ\\s]+$')])),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estado Operativo',
                'verbose_name_plural': 'Estados Operativos',
                'db_table': 'operational_statuses',
            },
        ),
        migrations.CreateModel(
            name='PhysicalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=1, unique=True, validators=[django.core.validators.RegexValidator(message='El código de estado físico debe contener exactamente 1 carácter alfanumérico (ej: "A", "I").', regex='^[A-Z]{1}$')])),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estado Físico',
                'verbose_name_plural': 'Estados Físicos',
                'db_table': 'physical_statuses',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator(message='El código del componente debe contener exactamente 4 dígitos numéricos (ej: "0001", "0012").', regex='^\\d{4}$')])),
                ('specification', models.TextField()),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.sector')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.componenttype')),
                ('operational_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.operationalstatus')),
                ('physical_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.physicalstatus')),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
                'db_table': 'components',
                'unique_together': {('sector', 'type', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ComponentCoord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('coords', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Ubicación WGS84')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.component')),
                ('criticality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.criticality')),
            ],
            options={
                'verbose_name': 'Coordenada de Componente',
                'verbose_name_plural': 'Coordenadas de Componentes',
                'db_table': 'components_coords',
            },
        ),
    ]
