# Generated by Django 6.0 on 2026-07-24 13:45

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Tipo de Coordenada',
                'verbose_name_plural': 'Tipos de Coordenadas',
                'db_table': 'type_coords',
            },
        ),
        migrations.CreateModel(
            name='Criticalities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Criticidad',
                'verbose_name_plural': 'Criticidades',
                'db_table': 'criticalities',
            },
        ),
        migrations.CreateModel(
            name='OperationalStatuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estado Operativo',
                'verbose_name_plural': 'Estados Operativos',
                'db_table': 'operational_statuses',
            },
        ),
        migrations.CreateModel(
            name='PhysicalStatuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estado Físico',
                'verbose_name_plural': 'Estados Físicos',
                'db_table': 'physical_statuses',
            },
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=7, unique=True)),
                ('specification', models.TextField()),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.sector')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.componenttypes')),
                ('operational_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.operationalstatuses')),
                ('physical_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.physicalstatuses')),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
                'db_table': 'components',
            },
        ),
        migrations.CreateModel(
            name='ComponentsCoords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('coords', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Ubicación WGS84')),
                ('component_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.components')),
                ('criticality_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.criticalities')),
            ],
            options={
                'verbose_name': 'Coordenada de Componente',
                'verbose_name_plural': 'Coordenadas de Componentes',
                'db_table': 'components_coords',
            },
        ),
    ]
