# Generated by Django 6.0 on 2026-07-23 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='components',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='componentscoords',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='componenttypes',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='criticalities',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='operationalstatuses',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='physicalstatuses',
            managers=[
            ],
        ),
    ]
