# Generated by Django 6.0 on 2026-07-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='componentcoord',
            index=models.Index(fields=['coords'], name='components__coords_518726_idx'),
        ),
        migrations.AddIndex(
            model_name='componentcoord',
            index=models.Index(fields=['component', 'criticality'], name='components__compone_b03e39_idx'),
        ),
    ]
