# Generated by Django 6.0 on 2026-09-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_componentcoord_components__coords_518726_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='componentcoord',
            name='components__coords_518726_idx',
        ),
        migrations.AddField(
            model_name='criticality',
            name='severity_level',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Nivel de Severidad (Mayor número = Mayor peligro)'),
        ),
        migrations.AlterField(
            model_name='criticality',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
